"""add click event idempotency

Revision ID: 8460c0f7d2d4
Revises: 453b421c5672
Create Date: 2026-05-29 13:27:46.835383
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8460c0f7d2d4'
down_revision: Union[str, None] = '453b421c5672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('click_events', sa.Column('event_id', sa.String(length=64), nullable=False))
    op.create_unique_constraint('uq_click_events_event_id', 'click_events', ['event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_click_events_event_id', 'click_events', type_='unique')
    op.drop_column('click_events', 'event_id')
    # ### end Alembic commands ###
